version: '3.8'
services:
  sshfs:
    restart: unless-stopped
    container_name: my-sshfs
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    build:
      context: .
      dockerfile: dockerfile
    image: topor:sshfs
    environment:
      - USER_ID
      - GROUP_ID
      - SSHFS_USER
      - SSHFS_HOST
      - SSHFS_PORT
      - SSHFS_HOST_PATH
      - TZ
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${SSHFS_LOCAL_PATH}:/mnt/files:rshared
      - ${SSH_CONFIG_DIR}:/root/.ssh:ro

